# Publish all joint states -----------------------------------
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 25

# Position Controllers ---------------------------------------
joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: servo1_link1_joint
    pid: { p: 5.0, i: 0.0, d: 0.01 }

joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: servo2_link2_joint
    pid: { p: 5.0, i: 0.0, d: 0.01 }

joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: servo3_link3_joint
    pid: { p: 5.0, i: 0.0, d: 0.01 }
