arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - servo1_link1_joint
    - servo2_link2_joint
    - servo3_link3_joint
  gains:
    servo1_link1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    servo2_link2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    servo3_link3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1