controller_list:
  - name: arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - servo1_link1_joint
      - servo2_link2_joint
      - servo3_link3_joint